# project_id = ""
db_name            = "example-postgres-private"
postgresql_version = "POSTGRES_9_6"
tier               = "db-f1-micro"
disk_size          = 10
disk_type          = "PD_SSD"
network_name       = "psql-example"
region             = "us-east1"
zone               = "c"
