apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
  # UNCOMMENT ME TO MAKE ME THE DEFAULT STORAGE CLASS (Note: you can only have one)
  annotations:
    "storageclass.kubernetes.io/is-default-class": "true"
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
