# Source: https://github.com/kubernetes-incubator/external-storage/tree/nfs-provisioner-v2.2.2/nfs/deploy/kubernetes/class.yaml

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: example-nfs
  annotations:
    "storageclass.kubernetes.io/is-default-class": "true"
provisioner: example.com/nfs
mountOptions:
  - vers=4.1
