module "cloud" {
  source = "./aws"
  is_enabled = "${var.provider_name == "aws" ? "true" : "false"}"
  masters = "${var.provider_master_count}"
  workers = "${var.provider_worker_count}"
  az_region = "${var.provider_region}"
  az_master_image = "${var.provider_master_image}"
  az_worker_image = "${var.provider_worker_image}"
  az_bastion_image = "${var.provider_bastion_image}"
  az_vpc_cidr = "${var.provider_vpc_cidr}"
//  zone = "${var.subnetaz}"
//  zone = "us-east-1a"
  az_cluster_ssh_user = "${var.provider_cluster_ssh_user}"
  az_bastion_ssh_user = "${var.provider_bastion_ssh_user}"
  key_name = "${var.provider_key_name}"
  prefix = "${var.provider_prefix}"
  public_key_path = "${var.provider_public_key_path}"
  private_key_path = "${var.provider_private_key_path}"
  instance_create_timeout = "${var.provider_instance_create_timeout}"
}
