module "cloud" {
  source = "./gcp"
  is_enabled = "${var.provider_name == "gcp" ? "true" : "false"}"
  masters = "${var.provider_master_count}"
  workers = "${var.provider_worker_count}"
  gp_project_name= "${var.provider_project_name}"
  gp_region = "${var.provider_region}"
  gp_zone   = "${var.provider_zone}"
  gp_master_image = "${var.provider_master_image}"
  gp_worker_image = "${var.provider_worker_image}"
  gp_bastion_image = "${var.provider_bastion_image}"
  gp_master_extra_disk_size_gb = "${var.provider_master_extra_disk_size_gb}"
  gp_worker_extra_disk_size_gb = "${var.provider_worker_extra_disk_size_gb}"
  gp_vpc_cidr = "${var.provider_vpc_cidr}"
  gp_cluster_ssh_user = "${var.provider_cluster_ssh_user}"
  gp_bastion_ssh_user = "${var.provider_bastion_ssh_user}"
  key_name = "${var.provider_key_name}"
  prefix = "${var.provider_prefix}"
  account_file_path = "${var.provider_account_file_path}"
  public_key_path = "${var.provider_public_key_path}"
  private_key_path = "${var.provider_private_key_path}"
  instance_create_timeout = "${var.provider_instance_create_timeout}"
  ssh_source_range_ips = "${var.provider_ssh_source_range_ips}"
}

